---
title: "HRA-Pop Cell Type Correlation Analysis Notebook"
output: html_document
---

# Environment

```{r message=FALSE, warning=FALSE}
library(tidyr)
library(knitr)
library(dplyr)
library(stringr)
library(ggplot2)
library(magrittr)
options(scipen=999)
```
 
# Load Data

```{r data}
data <- read.csv("https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/main/output-data/v0.10.2/reports/atlas/validation-v6.csv", 
                 header=T, fileEncoding = "UTF8")
```

# Prepare Data

```{r data prep}
# Clean up organ label strings
data$organ <- data$organ %>%
  str_replace("left ", "") %>%
  str_replace("right ", "") %>%
  str_replace("Set of ", "") %>%
  str_replace("left ", "") %>%
  str_replace(" of body", "") %>% 
  str_replace("respiratory system","lung") %>%
  str_replace("male reproductive system","prostate") %>%
  str_to_title()

# Clean up anatomical structure strings
data$as <- data$as %>%
  str_replace(" of urinary bladder", "") %>%
  str_replace(" of prostate", "") %>%
  str_replace(" of kidney", "") %>%
  str_replace(" of liver", "") %>%
  str_replace(" of heart", "") %>%
  str_replace("heart ", "") %>%
  str_replace(" of spleen", "") %>%
  str_replace(" of body", "") %>%
  str_trim() %>%
  str_to_title() %>%
  str_replace("Of", "of")

# Remove spatial data
data <- data[data$modality!="sc_proteomics",]

# Combine cell_id and cell_label
data$cell_name <- paste0(data$cell_id,"-",data$cell_label)
```

# Heatmaps Analysis

## Azimuth

```{r heatmap_azimuth_v0.2, fig.height=12, fig.width=24}
# Create pivot
data_azimuth <- 
  data %>% 
  filter(tool == "azimuth") %>%
  select(organ, as, as_id, cell_name, percentage) %>%
  pivot_wider(names_from = cell_name,
              values_from = percentage,
              values_fill = 0,
              values_fn = mean) %>%
  arrange(organ, as_id)

# Convert DF to a matrix
data_azimuth_heatmap <- data.matrix(data_azimuth[,4:ncol(data_azimuth)])

# Assign Row.names as organs
rownames(data_azimuth_heatmap) <- 
  paste0(data_azimuth$organ,"-",data_azimuth$as)
data_azimuth_heatmap <- 
  data_azimuth_heatmap[order(row.names(data_azimuth_heatmap)),]

# Scale data
data_azimuth_heatmap <- scale(data_azimuth_heatmap)

# Generate heatmap
heatmap_plot <- pheatmap::pheatmap(data_azimuth_heatmap, legend=TRUE,
                                   legend_breaks = c(0, 1, 2, 3, 
                                                     max(data_azimuth_heatmap)),
                                   legend_labels = c("0", "1", "2", "3", 
                                     "Percentage (z-scale)\n"))

ggsave(file=paste0("../output/heatmaps/organ_as_celltype-heatmap-azimuth.pdf"),
       heatmap_plot, width=24, height=12, units="in")
ggsave(file=paste0("../output/heatmaps/organ_as_celltype-heatmap-azimuth.png"),
       heatmap_plot, width=24, height=12, units="in")

heatmap_plot
```

## CellTypist

```{r heatmap_celltypist_v0.2, fig.height=12, fig.width=36}
# Create pivot
data_celltypist <- 
  data %>% 
  filter(tool == "celltypist") %>%
  select(organ, as, as_id, cell_name, percentage) %>%
  pivot_wider(names_from = cell_name,
              values_from = percentage,
              values_fill = 0,
              values_fn = mean) %>%
  arrange(organ, as_id)

# Convert DF to a matrix
data_celltypist_heatmap <- data.matrix(data_celltypist[,4:ncol(data_celltypist)])

# Assign Row.names as organs
rownames(data_celltypist_heatmap) <- 
  paste0(data_celltypist$organ,"-",data_celltypist$as)
data_celltypist_heatmap <- 
  data_celltypist_heatmap[order(row.names(data_celltypist_heatmap)),]

# Scale data
data_celltypist_heatmap <- scale(data_celltypist_heatmap)

# Generate heatmap
heatmap_plot <- pheatmap::pheatmap(data_celltypist_heatmap, legend=TRUE,
                                   legend_breaks = c(0, 1, 2, 3, 
                                                     max(data_celltypist_heatmap)),
                                   legend_labels = c("0", "1", "2", "3", 
                                     "Percentage (z-scale)\n"))

ggsave(file=paste0("../output/heatmaps/organ_as_celltype-heatmap-celltypist.pdf"),
       heatmap_plot, width=36, height=12, units="in")
ggsave(file=paste0("../output/heatmaps/organ_as_celltype-heatmap-celltypist.png"),
       heatmap_plot, width=36, height=12, units="in")

heatmap_plot
```

## PopV

```{r heatmap_popV_v0.2, fig.height=12, fig.width=24}
# Create pivot
data_popv <- 
  data %>% 
  filter(tool == "popv") %>%
  select(organ, as, as_id, cell_name, percentage) %>%
  pivot_wider(names_from = cell_name,
              values_from = percentage,
              values_fill = 0,
              values_fn = mean) %>%
  arrange(organ, as_id)

# Convert DF to a matrix
data_popv_heatmap <- data.matrix(data_popv[,4:ncol(data_popv)])

# Assign Row.names as organs
rownames(data_popv_heatmap) <- 
  paste0(data_popv$organ,"-",data_popv$as)
data_popv_heatmap <- 
  data_popv_heatmap[order(row.names(data_popv_heatmap)),]

# Scale data
data_popv_heatmap <- scale(data_popv_heatmap)

# Generate heatmap
heatmap_plot <- pheatmap::pheatmap(data_popv_heatmap, legend=TRUE,
                                   legend_breaks = c(0, 1, 2, 3, 
                                                     max(data_popv_heatmap)),
                                   legend_labels = c("0", "1", "2", "3", 
                                     "Percentage (z-scale)\n"))

ggsave(file=paste0("../output/heatmaps/organ_as_celltype-heatmap-popv.pdf"),
       heatmap_plot, width=24, height=12, units="in")
ggsave(file=paste0("../output/heatmaps/organ_as_celltype-heatmap-popv.png"),
       heatmap_plot, width=24, height=12, units="in")

heatmap_plot
```