---
title: "HRA-Pop Cell Type Correlation Analysis Notebook"
output: html_document
---

# Environment

```{r message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)
library(plyr)
library(knitr)
library(stringr)
library(ggplot2)
library(magrittr)
options(scipen=999)

knitr::opts_chunk$set(
    dev = c('pdf', 'png'), 
    fig.align = 'center',
    fig.path = 'figs/',
    pdf.options(encoding = "default")) 
```
 
# Load Data

```{r data}
#### Paths ####
##### X-Atlas Consortia API #####
# Select Branch 
# Maing
api_url <- c("https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/main/output-data/")

# Testing
#api_url <- c("https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/refs/heads/v1.0/output-data/")

# Version
output_data_dir <- c("v1.0")

##### Project paths #####
path_validation <- paste0("./validations/")

#### Load Data ####
# Data set metadata
metadata <- read.csv(paste0(api_url,output_data_dir,
                            "/reports/atlas-ad-hoc/as-datasets-modality.csv"),
                     header=T, fileEncoding = "UTF8")

# Cell type cross-walk
cell_lookup <- read.csv(paste0(api_url,output_data_dir,
                            "/reports/atlas-ad-hoc/cell-types-level-mapping.csv"),
                        header=T, fileEncoding = "UTF8")

# Data for heatmaps
# Includes organ, anatomical structure, cell types measures by tool and donor gender
data <- read.csv(paste0(api_url,output_data_dir,
                        "/reports/atlas/validation-v6.csv"), 
                 header=T, fileEncoding = "UTF8")

# Spatial data aggregation: Organs Small & Large Intestines, AS, cell types measures
data_spatial <- read.csv("../heatmaps/spatial/HRApop_Spatial_OASCT_CellCount_Percentage.csv",
                         header=T)
```

# Prepare Data Files

```{r metadata-crosswalk-prep}
#### Prepare Anatomical Structure Metadata ####
metadata$organ_label <- 
  metadata$organ_label %>% 
    str_to_lower() %>%
    str_replace("set of lactiferous glands in right breast","breast") %>%
    str_replace("set of lactiferous glands in left breast","breast") %>%
    str_replace("respiratory system", "lung") %>%
    str_replace("male reproductive system","prostate") %>%
    str_replace(" of body","") %>%
    str_replace("right ","") %>%
    str_replace("left ","") %>%
    str_to_title()

metadata$as_label <- 
  metadata$as_label %>% 
  str_to_lower() %>%
  str_replace("right cardiac ","right ") %>%
  str_replace("left cardiac ","left ") %>%
  str_replace("posteromedial head of posterior papillary muscle of ","") %>%
  str_replace("right posterior ","posterior ") %>%
  str_replace("left posterior ","posterior ") %>%
  str_replace("right anterior ","anterior ") %>%
  str_replace("left anterior ","anterior ") %>%
  str_replace("right medial ","medial ") %>%
  str_replace("left medial ","medial ") %>%
  str_replace("right lateral ","lateral ") %>%
  str_replace("left lateral ","lateral ") %>%
  str_replace("right apical ","apical ") %>%
  str_replace("left apical ","apical ") %>%
  str_replace("right superior ","superior ") %>%
  str_replace("left superior ","superior ") %>%
  str_replace("right thymus ","") %>%
  str_replace("left thymus ","") %>%
  str_replace("right ureter","ureter") %>%
  str_replace("left ureter","ureter") %>%
  str_replace("of right ","") %>%
  str_replace("of left ","") %>%
  str_replace("of body ","") %>%
  str_replace("part of ","") %>%
  str_replace("heart ","") %>%
  str_replace("kidney ","") %>%
  str_replace(" of prostate","") %>%
  str_replace(" of pancreas","") %>%
  str_replace(" of spleen","") %>%
  str_replace(" of the liver","") %>%
  str_replace(" of liver","") %>%
  str_replace(" of kidney","") %>%
  str_replace(" of urinary bladder","") %>%
  str_to_title()

metadata <-
  metadata %>%
  select(modality,tool,organ_label,as_label,dataset) %>% 
  distinct() %>%
  arrange(organ_label,as_label,modality,tool) %>%
  ddply(.(tool,organ_label,as_label), summarise,
        ds_count = length(unique(dataset)))%>%
  arrange(organ_label,tool,ds_count) %>%
  plyr::rename(c("organ_label" = "organ",
                 "as_label" = "as"))

# Save results
# write.csv(metadata,"../heatmaps/HRApop_organ_dataset_metadata_pivot.csv",
#           row.names = F)

# Calculate summary statistics for metadata analysis
metadata_pivot <- 
  metadata %>%
  ddply(.(organ), summarise,
        AS = length(unique(as)),
        Tools = length(unique(tool)),
        Median_Data_Set_Count = median(ds_count),
        Min_Data_Set_Count = min(ds_count),
        Max_Data_Set_Count = max(ds_count)) %>%
  arrange(desc(AS), desc(Tools), desc(Median_Data_Set_Count), organ) %>%
  plyr::rename(c("organ"="Organ"))

# Save results
metadata_pivot
write.csv(metadata_pivot,"../heatmaps/HRApop_organ_dataset_metadata_pivot2.csv",
          row.names = F)

#### Prepare Cell Type Cross-walk ####
# Change Cell Labels to Title Case
cell_lookup$cell_label <- str_to_title(cell_lookup$cell_label)
cell_lookup$level_1_cell_label <- str_to_title(cell_lookup$level_1_cell_label)

# Update cell_id variable
cell_lookup$cell_id <-
  str_replace(cell_lookup$cell_id,"http://purl.obolibrary.org/obo/","")
cell_lookup$cell_id <- 
  str_replace(cell_lookup$cell_id,"_","\\:")
```


```{r data-prep}
#### Prepare Cell Type Data Sets ####
# Clean up organ label strings
data$sex <- factor(data$sex)

# Prepare Tool
data$tool <- 
  factor(data$tool, levels=c("azimuth","celltypist","popv","sc_proteomics"),
                    labels=c("Azimuth","CellTypist","popV","SC Proteomics"))

# Prepare organ labels
data$organ <- 
  data$organ %>% 
  str_to_lower() %>%
  str_replace("set of lactiferous glands in right breast","breast") %>%
  str_replace("set of lactiferous glands in left breast","breast") %>%
  str_replace("respiratory system", "lung") %>%
  str_replace("male reproductive system","prostate") %>%
  str_replace(" of body","") %>%
  str_replace("right ","") %>%
  str_replace("left ","") %>%
  str_to_title()
data$organ <- factor(data$organ)

# Prepare anatomical structure labels
data$as <- 
  data$as %>% 
  str_to_lower() %>%
  str_replace("right cardiac ","right ") %>%
  str_replace("left cardiac ","left ") %>%
  str_replace("posteromedial head of posterior papillary muscle of ","") %>%
  str_replace("right posterior ","posterior ") %>%
  str_replace("left posterior ","posterior ") %>%
  str_replace("right anterior ","anterior ") %>%
  str_replace("left anterior ","anterior ") %>%
  str_replace("right medial ","medial ") %>%
  str_replace("left medial ","medial ") %>%
  str_replace("right lateral ","lateral ") %>%
  str_replace("left lateral ","lateral ") %>%
  str_replace("right apical ","apical ") %>%
  str_replace("left apical ","apical ") %>%
  str_replace("right superior ","superior ") %>%
  str_replace("left superior ","superior ") %>%
  str_replace("right thymus ","") %>%
  str_replace("left thymus ","") %>%
  str_replace("right ureter","ureter") %>%
  str_replace("left ureter","ureter") %>%
  str_replace("of right ","") %>%
  str_replace("of left ","") %>%
  str_replace("of body ","") %>%
  str_replace("part of ","") %>%
  str_replace("heart ","") %>%
  str_replace("kidney ","") %>%
  str_replace(" of prostate","") %>%
  str_replace(" of pancreas","") %>%
  str_replace(" of spleen","") %>%
  str_replace(" of the liver","") %>%
  str_replace(" of liver","") %>%
  str_replace(" of kidney","") %>%
  str_replace(" of urinary bladder","") %>%
  str_to_title()

# Update cell_label variable
data$cell_label <- data$cell_label %>%
  str_replace("_"," ") %>%
  str_to_title()

# Update cell labels for data_spatial
data_spatial$cell_label <- data_spatial$cell_type
# data_spatial$cell_label <- str_to_title(data_spatial$cell_label)
data_spatial <- 
   data_spatial %>%
   rename(c("organ_label"="organ",
            "uberon_id"="as_id"))
```

```{r prepare_cell_type_names}
#### Create data subsets based on data analysis tool ####
# Azimuth
data_azimuth <-
  data %>%
  filter(tool=="Azimuth") %>%
  select(-asct_relation_in_asctb_table,-indirect_asct_relation_in_asctb_table)
# Cell Typist
data_celltypist <-
  data %>%
  filter(tool=="CellTypist") %>%
  select(-asct_relation_in_asctb_table,-indirect_asct_relation_in_asctb_table)
# PopV
data_popv <-
  data %>%
  filter(tool=="popV") %>%
  select(-asct_relation_in_asctb_table,-indirect_asct_relation_in_asctb_table)
# SC Proteomics 
data_spatial <-
  data_spatial %>%
  filter(tool=="Spatial")

#### Update Cell Type Names ####
# Azimuth
data_azimuth <-
  left_join(data_azimuth, cell_lookup[,c(2,4)], by="cell_id") %>%
  rename(c("level_1_cell_label" = "cell_label.level_1"))
# Cell Typist
data_celltypist <-
  left_join(data_celltypist, cell_lookup[,c(2,4)], by="cell_id") %>%
  rename(c("level_1_cell_label" = "cell_label.level_1"))
# PopV
data_popv <-
  left_join(data_popv, cell_lookup[,c(2,4)], by="cell_id") %>%
  rename(c("level_1_cell_label" = "cell_label.level_1"))
# SC Proteomics 
# data_spatial <-
#   left_join(data_spatial, cell_lookup[,c(1,4)], by="cell_label") %>%
#   rename(c("level_1_cell_label" = "cell_label2"))
```

# Heatmaps Analysis

## Azimuth

```{r heatmap_azimuth_v0.2, fig.height=12, fig.width=24}
# Create pivot
data_azimuth <- 
  data_azimuth %>%
  select(organ, as, cell_label, percentage) %>%
  pivot_wider(names_from = cell_label,
              values_from = percentage,
              values_fill = 0,
              values_fn = mean) %>%
  arrange(organ, as)

# Convert DF to a matrix
data_azimuth_heatmap <- data.matrix(data_azimuth[,4:ncol(data_azimuth)])

# Assign Row.names as organs
rownames(data_azimuth_heatmap) <- 
  paste0(data_azimuth$organ,"-",data_azimuth$as)
data_azimuth_heatmap <- 
  data_azimuth_heatmap[order(row.names(data_azimuth_heatmap)),]

# Scale data
data_azimuth_heatmap <- scale(data_azimuth_heatmap)

# Generate heatmap
heatmap_plot <- pheatmap::pheatmap(data_azimuth_heatmap, legend=TRUE,
                                   legend_breaks = c(-1, 0, 1, 2, 3, 4, 5,
                                                     max(data_azimuth_heatmap)),
                                   legend_labels = c("-1", "0", "1", "2", "3", "4", "5",
                                     "Percentage (z-scale)\n"))

# Plot
heatmap_plot
```

## CellTypist

```{r heatmap_celltypist_v0.2, fig.height=12, fig.width=36}
# Create pivot
data_celltypist <- 
  data_celltypist %>% 
  select(organ, as, cell_label, percentage) %>%
  pivot_wider(names_from = cell_label,
              values_from = percentage,
              values_fill = 0,
              values_fn = mean) %>%
  arrange(organ, as)

# Convert DF to a matrix
data_celltypist_heatmap <- data.matrix(data_celltypist[,4:ncol(data_celltypist)])

# Assign Row.names as organs
rownames(data_celltypist_heatmap) <- 
  paste0(data_celltypist$organ,"-",data_celltypist$as)
data_celltypist_heatmap <- 
  data_celltypist_heatmap[order(row.names(data_celltypist_heatmap)),]

# Scale data
data_celltypist_heatmap <- scale(data_celltypist_heatmap)

# Generate heatmap
heatmap_plot <- pheatmap::pheatmap(data_celltypist_heatmap, legend=TRUE,
                                   legend_breaks = c(-1,0, 1, 2, 3, 4, 5, 6,
                                                     max(data_celltypist_heatmap)),
                                   legend_labels = c("-1","0", "1", "2", "3", "4","5","6",
                                     "Percentage (z-scale)\n"))


# Plot
heatmap_plot
```

## PopV

```{r heatmap_popV_v0.2, fig.height=12, fig.width=24}
# Create pivot
data_popv <- 
  data_popv %>%
  select(organ, as, cell_label, percentage) %>%
  pivot_wider(names_from = cell_label,
              values_from = percentage,
              values_fill = 0,
              values_fn = mean) %>%
  arrange(organ, as)

# Convert DF to a matrix
data_popv_heatmap <- data.matrix(data_popv[,4:ncol(data_popv)])

# Assign Row.names as organs
rownames(data_popv_heatmap) <- 
  paste0(data_popv$organ,"-",data_popv$as)
data_popv_heatmap <- 
  data_popv_heatmap[order(row.names(data_popv_heatmap)),]

# Scale data
data_popv_heatmap <- scale(data_popv_heatmap)

# Generate heatmap
heatmap_plot <- pheatmap::pheatmap(data_popv_heatmap, legend=TRUE,
                                   legend_breaks = c(-1, 0, 1, 2, 3, 4, 5,6,
                                                     max(data_popv_heatmap)),
                                   legend_labels = c("-1", "0", "1", "2", "3", 
                                                     "4", "5","6",
                                                     "Percentage (z-scale)\n"))
# Plot
heatmap_plot
```

## SC Proteomics

```{r heatmap_scproteomics_v0.1, fig.height=6.5, fig.width=12}
# Create pivot
data_scproteomics <- 
  data_spatial %>%
  select(organ, as, as_id, cell_label, percentage) %>%
  pivot_wider(names_from = cell_label,
              values_from = percentage,
              values_fill = 0,
              values_fn = mean) %>%
  arrange(organ, as_id)

# Convert DF to a matrix
data_scproteomics_heatmap <- data.matrix(data_scproteomics[,4:ncol(data_scproteomics)])

# Assign Row.names as organs
rownames(data_scproteomics_heatmap) <- 
  paste0(data_scproteomics$organ,"-",data_scproteomics$as)
data_scproteomics_heatmap <- 
  data_scproteomics_heatmap[order(row.names(data_scproteomics_heatmap)),]

# Scale data
data_scproteomics_heatmap <- scale(data_scproteomics_heatmap)

# Generate heatmap
heatmap_plot <- pheatmap::pheatmap(data_scproteomics_heatmap, legend=TRUE,
                                  legend_breaks = c(-2, -1, 0, 1, 2, 3,
                                                    max(data_scproteomics_heatmap)),
                                  legend_labels = c(-2, -1, 0, 1, 2, 3,
                                                    "Percentage (z-scale)\n"))


# Plot
heatmap_plot
```
